package retailfoodapplication;

/////////////////////////////
// DO NOT EDIT THIS FILE
/////////////////////////////

/**
 * Small stub class to load the GUI.
 * 
 * @author bdorn
 *
 */
public class RetailFoodDriver
{	
	/**
	 * Loads the underlying application.
	 * 
	 * @param args Command line arguments, not used.
	 */
	public static void main(String[] args) 
	{
		RetailFoodApplication app = new RetailFoodApplication();
		app.setupGUI();		
	}
}
